# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christian Forcada Vitalla
author: Christian Forcada Vitalla
email: chris.forcadavitalla@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Soy Christian Forcada Vitalla (txtbits) y este es mi espacio para compartir conocimientos en desarrollo de software y cualquier otro interés.
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://txtbits.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title.html
twitter_username: txtbits
github_username: txtbits
linkedin_username: christianforcadavitalla

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 4
paginate_path: "/blog/pagina/:num/"
show_excerpts: true

disqus:
    shortname: txtbits

months:
  - Enero
  - Febrero
  - Marzo
  - Abril
  - Mayo
  - Junio
  - Julio
  - Agosto
  - Septiembre
  - Octubre
  - Noviembre
  - Diciembre

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
